# Generated by Django 4.0 on 2021-12-21 02:08

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models

from products.models import Product
from questions.models import Question


def gen_master(apps, schema_editor):
    product = Product.objects.get(id=1)
    product_content_type = ContentType.objects.get_for_model(product)
    Question(user_id=2, content_type=product_content_type, object_id=product.id, body="이거 물빠짐 심한가요?").save()
    Question(user_id=3, content_type=product_content_type, object_id=product.id, body="이거 입으면 인싸?").save()

    product = Product.objects.get(id=2)
    product_content_type = ContentType.objects.get_for_model(product)
    Question(user_id=1, content_type=product_content_type, object_id=product.id, body="이거 원단이 튼튼한가요?").save()
    Question(user_id=3, content_type=product_content_type, object_id=product.id, body="이거 세탁해도 되나요?").save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('object_id', models.PositiveIntegerField(verbose_name='관련 데이터 번호')),
                ('body', models.TextField(verbose_name='내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='답변완료여부')),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_type_question',
                                   to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('body', models.TextField(verbose_name='내용')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.RunPython(gen_master),
    ]
